name: LabSMP
version: '${project.version}'
main: org.labgames.smp.SMP
api-version: 1.19
author: LabGames
commands:
  help:
    description: 'Open help menu'
  spawn:
    description: 'Teleport to spawn'
  setspawn:
    description: 'Set spawn point'
    permission: 'smp.admin'
  homes:
    description: 'List your homes'
  home:
    description: 'Teleport  home'
  sethome:
    description: 'Create a home'
  delhome:
    description: 'Delete a home'
  tpa:
    description: 'Send a teleport request'
  tpaccept:
    description: 'Accept a teleport request'
  kit:
    description: 'Claim a kit'
  kits:
    description: 'List kits'
  givekit:
    description: 'Admin command for giving kits'
    permission: 'smp.admin'
  message:
    aliases: [msg,m,tell]
  reply:
    aliases: [r]
permissions:
  smp.admin:
    default: op
  smp.homes.2:
    default: true