name: LabSMP
version: '${project.version}'
main: org.labgames.smp.SMP
api-version: 1.19
author: LabGames
commands:
  spawn:
    description: 'Teleport to spawn'
  setspawn:
    description: 'Set spawn point'
    permission: 'smp.admin'
  homes:
    description: 'List your homes'
  home:
    description: 'Teleport  home'
  sethome:
    description: 'Create a home'
  delhome:
    description: 'Delete a home'
permissions:
  smp.admin:
    default: op
  smp.homes.2:
    default: true